CREATE-SCHEMA webuser AUTHORIZATION postgres;

DROP TABLE WEBUSER.TB_AGENDAMENTOS;
DROP TABLE WEBUSER.TB_ATIVIDADES;
DROP TABLE WEBUSER.TB_INSTRUTORES;
DROP TABLE WEBUSER.TB_MEMBROS;
DROP TABLE WEBUSER.TB_PLANOS;

CREATE TABLE WEBUSER.TB_INSTRUTORES(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    SOBRENOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ENDERECO TEXT,
    TELEFONE VARCHAR(255) NOT NULL
);

CREATE TABLE WEBUSER.TB_PLANOS(
    ID SERIAL PRIMARY KEY,
    PLANO VARCHAR(255) NOT NULL
);

CREATE TABLE WEBUSER.TB_MEMBROS(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    SOBRENOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ENDERECO TEXT,
    TELEFONE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TIPO_PLANO INT REFERENCES WEBUSER.TB_PLANOS,
    DATA_INICIO DATE NOT NULL,
    ATIVO BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_ATIVIDADES(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    INSTRUTOR INTEGER REFERENCES WEBUSER.TB_INSTRUTORES(ID) ON DELETE CASCADE,
    DATA TIMESTAMP NOT NULL,
    DURACAO INT NOT NULL,
    CAPACIDADE INT NOT NULL,
    TIPO_PLANO INT REFERENCES WEBUSER.TB_PLANOS(ID),
    ATIVO BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_AGENDAMENTOS(
    ID SERIAL PRIMARY KEY,
    ATIVIDADE INTEGER REFERENCES WEBUSER.TB_ATIVIDADES(ID) ON DELETE CASCADE,
    MEMBRO INTEGER REFERENCES WEBUSER.TB_MEMBROS(ID) ON DELETE CASCADE
);




